development:
  adapter: postgresql
  encoding: unicode
  database: alchemy_development
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: alchemy_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: alchemy_test
  pool: 5