# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db0ae92a63932e054880ee1da19872b2f16bcef1257e342fb8d4958530ad3316383ee02b3dd5f2e1466fb1e64d89bf16f36d91bdce9e86ecb17968c5906e4c1e

test:
  secret_key_base: 20976b5e357b0890c4ac4eafc2a1a64becf0083359e3dff68e171b99cbfcebf202603e39d08c477becedfe39ac3d93404a794d01a893eba8d51f2b34ca0bef18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
